/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const risks_Logic = require('./code/risks-logic');

class riskManagementSrv extends LCAPApplicationService {
    async init() {

        this.after('READ', 'Risks', async (results, request) => {
            await risks_Logic(results, request);
        });

        return super.init();
    }
}


module.exports = {
    riskManagementSrv
};